package com.example.oracleapi.Model;

public enum ConsultaStatus {
    AGENDADA("Agendada"),
    CONFIRMADA("Confirmada"),
    CANCELADA_PELO_PACIENTE("Cancelada pelo paciente"),
    CANCELADA_PELO_MEDICO("Cancelada pelo médico"),
    REMARCADA_PELO_PACIENTE("Remarcada pelo paciente"),
    REMARCADA_PELO_MEDICO("Remarcada pelo médico"),
    FINALIZADA("Finalizada"),
    EM_ANDAMENTO("Em andamento"),
    AGUARDANDO_ATENDIMENTO("Aguardando atendimento"),
    NA_SALA_DE_ESPERA("Na sala de espera"),
    CHECK_IN_REALIZADO("Check-in realizado"),
    NA_SALA_DE_EXAMES("Na sala de exames"),
    EM_REVISÃO("Em revisão"),
    PRESCRIÇÃO_REALIZADA("Prescrição realizada"),
    RECEITA_ENTREGUE("Receita entregue"),
    EXAMES_SOLICITADOS("Exames solicitados"),
    EXAMES_ENTREGUES("Exames entregues"),
    RESULTADOS_DISPONIVEIS("Resultados disponíveis"),
    LAUDO_CONCLUIDO("Laudo concluído"),
    PRONTA_PARA_FATURAMENTO("Pronta para faturamento"),
    FATURADA("Faturada"),
    PAGA("Paga"),
    EM_COBRANCA("Em cobrança"),
    EM_NEGOCIACAO("Em negociação"),
    ATRASADA("Atrasada"),
    AGUARDANDO_PAGAMENTO("Aguardando pagamento"),
    EM_ANALISE("Em análise"),
    AUTORIZADA_PELO_CONVENIO("Autorizada pelo convênio"),
    NAO_AUTORIZADA_PELO_CONVENIO("Não autorizada pelo convênio"),
    AGUARDANDO_AUTORIZACAO("Aguardando autorização"),
    AGUARDANDO_DOCUMENTOS("Aguardando documentos"),
    DOCUMENTOS_COMPLETOS("Documentos completos"),
    REAGENDADA_POR_FALTA("Reagendada por falta"),
    NAO_COMPARECEU("Não compareceu"),
    SEM_CONTATO("Sem contato"),
    PACIENTE_RECUSOU("Paciente recusou"),
    CANCELADA_SEM_CUSTO("Cancelada sem custo"),
    CANCELADA_COM_MULTA("Cancelada com multa"),
    PENDENTE_CONFIRMACAO("Pendente de confirmação"),
    EM_CONFIRMACAO("Em confirmação"),
    PACIENTE_NO_LOCAL("Paciente no local"),
    PACIENTE_EM_ATENDIMENTO("Paciente em atendimento"),
    ATENDIMENTO_FINALIZADO("Atendimento finalizado"),
    EM_OBSERVACAO("Em observação"),
    TRANSFERIDA_PARA_OUTRO_MEDICO("Transferida para outro médico"),
    TRANSFERIDA_PARA_OUTRO_SETOR("Transferida para outro setor"),
    TRANSFERIDA_PARA_OUTRO_DIA("Transferida para outro dia"),
    PACIENTE_DE_ALTA("Paciente de alta"),
    PACIENTE_INTERNADO("Paciente internado"),
    AGUARDANDO_CIRURGIA("Aguardando cirurgia"),
    EM_CIRURGIA("Em cirurgia"),
    CIRURGIA_CONCLUIDA("Cirurgia concluída"),
    EM_RECUPERACAO("Em recuperação"),
    EM_REABILITACAO("Em reabilitação"),
    EM_CUIDADOS_PALIATIVOS("Em cuidados paliativos"),
    AGUARDANDO_SEGUIMENTO("Aguardando seguimento"),
    SEGUIMENTO_REALIZADO("Seguimento realizado"),
    EM_TELECONSULTA("Em teleconsulta"),
    TELECONSULTA_CONCLUIDA("Teleconsulta concluída"),
    TELECONSULTA_CANCELADA("Teleconsulta cancelada"),
    TELECONSULTA_REMARCADA("Teleconsulta remarcada"),
    TELECONSULTA_EM_ANDAMENTO("Teleconsulta em andamento"),
    PRIORIDADE_ALTA("Prioridade alta"),
    PRIORIDADE_MEDIA("Prioridade média"),
    PRIORIDADE_BAIXA("Prioridade baixa"),
    PACIENTE_EM_VIAGEM("Paciente em viagem"),
    PACIENTE_IMPEDIDO("Paciente impedido"),
    PACIENTE_DEFERIDO("Paciente deferido"),
    PACIENTE_INDISPONIVEL("Paciente indisponível"),
    AGUARDANDO_CONSULTA("Aguardando consulta"),
    EM_PROCEDIMENTO("Em procedimento"),
    PROCEDIMENTO_CONCLUIDO("Procedimento concluído"),
    PROCEDIMENTO_CANCELADO("Procedimento cancelado"),
    AGUARDANDO_RESULTADOS("Aguardando resultados"),
    RESULTADOS_ENTREGUES("Resultados entregues"),
    PRONTO_PARA_ALTA("Pronto para alta"),
    AGUARDANDO_RETORNO("Aguardando retorno"),
    RETORNO_REALIZADO("Retorno realizado"),
    EM_SEGUIMENTO("Em seguimento"),
    EM_AVALIACAO("Em avaliação"),
    ALTA_MEDICA("Alta médica"),
    MONITORANDO_EFEITOS("Monitorando efeitos"),
    AGUARDANDO_REFERENCIA("Aguardando referência"),
    REFERENCIADO_PARA_ESPECIALISTA("Referenciado para especialista"),
    EM_TRATAMENTO_CONTINUADO("Em tratamento continuado"),
    EM_OBSERVACAO_DOMICILIAR("Em observação domiciliar"),
    EM_ACOMPANHAMENTO("Em acompanhamento"),
    EM_OBSERVACAO_PSIQUIATRICA("Em observação psiquiátrica"),
    AGUARDANDO_AUTORIZACAO_FAMILIAR("Aguardando autorização familiar"),
    PACIENTE_ABANDONOU("Paciente abandonou"),
    PACIENTE_EM_RECUPERACAO("Paciente em recuperação"),
    EM_CUIDADOS_CRITICOS("Em cuidados críticos"),
    EM_OBSERVACAO_URGENTE("Em observação urgente"),
    EM_OBSERVACAO_DE_ROTINA("Em observação de rotina"),
    AGUARDANDO_ALTA_HOSPITALAR("Aguardando alta hospitalar"),
    PACIENTE_LIBERADO("Paciente liberado"),
    CONSULTA_VIRTUAL("Consulta virtual"),
    CONSULTA_DOMICILIAR("Consulta domiciliar"),
    AGUARDANDO_TRANSPORTE("Aguardando transporte"),
    EM_TRANSPORTE("Em transporte"),
    PACIENTE_TRANSFERIDO("Paciente transferido"),
    CONSULTA_ENCERRADA("Consulta encerrada");

    private final String descricao;

    ConsultaStatus(String descricao) {
        this.descricao = descricao;
    }

    public String getDescricao() {
        return descricao;
    }
}
