package com.example.oracleapi.Model;

public enum EspecificacaoMedico {
    CARDIOLOGIA("Cardiologia"),
    PEDIATRIA("Pediatria"),
    ORTOPEDIA("Ortopedia"),
    NEUROLOGIA("Neurologia"),
    GINECOLOGIA("Ginecologia"),
    DERMATOLOGIA("Dermatologia"),
    PSIQUIATRIA("Psiquiatria"),
    ONCOLOGIA("Oncologia"),
    UROLOGIA("Urologia"),
    OFTALMOLOGIA("Oftalmologia"),
    OTORRINOLARINGOLOGIA("Otorrinolaringologia"),
    ANESTESIOLOGIA("Anestesiologia"),
    GASTROENTEROLOGIA("Gastroenterologia"),
    ENDOCRINOLOGIA("Endocrinologia"),
    REUMATOLOGIA("Reumatologia"),
    HEMATOLOGIA("Hematologia"),
    PNEUMOLOGIA("Pneumologia"),
    INFECTOLOGIA("Infectologia"),
    RADIOLOGIA("Radiologia"),
    CIRURGIA_GERAL("Cirurgia Geral"),
    CIRURGIA_PLASTICA("Cirurgia Plástica"),
    CIRURGIA_CARDIOVASCULAR("Cirurgia Cardiovascular"),
    MEDICINA_ESPORTIVA("Medicina Esportiva"),
    MEDICINA_NUCLEAR("Medicina Nuclear"),
    MEDICINA_INTENSIVA("Medicina Intensiva"),
    MEDICINA_PREVENTIVA("Medicina Preventiva"),
    NUTROLOGIA("Nutrologia"),
    ANGIOLOGIA("Angiologia"),
    HEPATOLOGIA("Hepatologia"),
    GENETICA_MEDICA("Genética Médica"),
    CIRURGIA_PEDIATRICA("Cirurgia Pediátrica"),
    CIRURGIA_ONCOLOGICA("Cirurgia Oncológica"),
    CIRURGIA_TORACICA("Cirurgia Torácica"),
    CIRURGIA_VASCULAR("Cirurgia Vascular"),
    CIRURGIA_BUCOMAXILOFACIAL("Cirurgia Bucomaxilofacial"),
    MEDICINA_DO_TRABALHO("Medicina do Trabalho"),
    MEDICINA_FAMILIAR("Medicina Familiar"),
    MEDICINA_LEGAL("Medicina Legal"),
    MEDICINA_HIPERBARICA("Medicina Hiperbárica"),
    MEDICINA_DO_SONO("Medicina do Sono"),
    MEDICINA_PALIATIVA("Medicina Paliativa"),
    ALERGOLOGIA("Alergologia"),
    IMUNOLOGIA("Imunologia"),
    SEXOLOGIA("Sexologia"),
    TOXICOLOGIA("Toxicologia"),
    MEDICINA_ESTETICA("Medicina Estética"),
    FONOAUDIOLOGIA("Fonoaudiologia"),
    ACUPUNTURA("Acupuntura"),
    RADIOTERAPIA("Radioterapia"),
    NEFROLOGIA("Nefrologia"),
    PROCTOLOGIA("Proctologia"),
    HANSENOLOGIA("Hanseníase"),
    TERAPIA_INTENSIVA_PEDIATRICA("Terapia Intensiva Pediátrica"),
    HEMODINAMICA("Hemodinâmica"),
    TRANSPLANTOLOGIA("Transplantologia"),
    TELEMEDICINA("Telemedicina"),
    GERIATRIA("Geriatria"),
    CLINICA_MEDICA("Clínica Médica"),
    TRAUMATOLOGIA("Traumatologia"),
    MASTOLOGIA("Mastologia"),
    EPIDEMIOLOGIA("Epidemiologia"),
    DOR_CRONICA("Dor Crônica"),
    FARMACOLOGIA_CLINICA("Farmacologia Clínica"),
    BIOINFORMATICA_MEDICA("Bioinformática Médica"),
    MEDICINA_DE_URGENCIA("Medicina de Urgência"),
    PSICOGERIATRIA("Psicogeriatria"),
    PSICOTERAPIA("Psicoterapia"),
    ULTRASSONOGRAFIA("Ultrassonografia"),
    ENDOCRINOLOGIA_PEDIATRICA("Endocrinologia Pediátrica"),
    PATOLOGIA_CLINICA("Patologia Clínica"),
    MEDICINA_REGENERATIVA("Medicina Regenerativa"),
    BIOETICA("Bioética"),
    PSICOSSOMATICA("Psicossomática"),
    GERAL("Geral");

    private final String descricao;

    EspecificacaoMedico(String descricao) {
        this.descricao = descricao;
    }

    public String getDescricao() {
        return descricao;
    }
}
